# Generated by Django 4.2.3 on 2023-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes', '0002_rename_stickynotes_stickynotes_stickynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynotes',
            name='StickyNote',
            field=models.TextField(),
        ),
    ]
