# Generated by Django 4.2.3 on 2023-07-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes', '0003_alter_stickynotes_stickynote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StickyNotes',
        ),
    ]
