# Generated by Django 4.2.3 on 2023-07-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickynotes', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='StickyNote',
            new_name='SNote',
        ),
    ]
