# Generated by Django 4.2.3 on 2023-08-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
