# Generated by Django 4.2.3 on 2023-08-15 16:46

import Notes.validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(limit_value=2), Notes.validator.validate_first_name_starts_with_letter])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(limit_value=1), Notes.validator.validate_last_name_starts_with_letter])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
                ('image_url', models.URLField()),
                ('age', models.IntegerField(default=18)),
            ],
        ),
    ]
