# Generated by Django 4.2.3 on 2023-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0007_alter_profile_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
