# Generated by Django 4.2.3 on 2023-08-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0008_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='Writer',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
